package tietorakenne.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tietorakenne.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.04.26 10:59:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AsoyTest {



  // Generated by ComTest BEGIN
  /** testGetAsoyNimi70 */
  @Test
  public void testGetAsoyNimi70() {    // Asoy: 70
    Asoy asoy1 = new Asoy(); 
    asoy1.taytaTestiTiedoilla(); 
    { String _l_=asoy1.getAsoyNimi(),_r_="ASOY.*"; if ( !_l_.matches(_r_) ) fail("From: Asoy line: 73" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi124 */
  @Test
  public void testRekisteroi124() {    // Asoy: 124
    Asoy asoy1 = new Asoy(); 
    assertEquals("From: Asoy line: 126", 0, asoy1.getTunnusNro()); 
    asoy1.rekisteroi(); 
    Asoy asoy2 = new Asoy(); 
    asoy2.rekisteroi(); 
    int n1 = asoy1.getTunnusNro(); 
    int n2 = asoy2.getTunnusNro(); 
    assertEquals("From: Asoy line: 132", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetAsoyHuolto157 */
  @Test
  public void testGetAsoyHuolto157() {    // Asoy: 157
    Asoy asoy1 = new Asoy(); 
    asoy1.taytaTestiTiedoilla(); 
    { String _l_=asoy1.getAsoyHuolto(),_r_="Huoltoyhtiö"; if ( !_l_.matches(_r_) ) fail("From: Asoy line: 160" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetAsoyOsoite178 */
  @Test
  public void testGetAsoyOsoite178() {    // Asoy: 178
    Asoy asoy1 = new Asoy(); 
    asoy1.taytaTestiTiedoilla(); 
    { String _l_=asoy1.getAsoyOsoite(),_r_="Esimerkkikatu.*"; if ( !_l_.matches(_r_) ) fail("From: Asoy line: 181" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString243 */
  @Test
  public void testToString243() {    // Asoy: 243
    Asoy asoy = new Asoy(); 
    asoy.parse("3|   ASOY Ankkalinna |  Katu 2  |10800|Ankkalinna     |   Isännöinti Siipiveikot   |   Huolto Räpylä"); 
    assertEquals("From: Asoy line: 246", true, asoy.toString().startsWith("3|ASOY Ankkalinna|Katu 2|10800|Ankkalinna|Isännöinti Siipiveikot|Huolto Räpylä")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse264 */
  @Test
  public void testParse264() {    // Asoy: 264
    Asoy asoy = new Asoy(); 
    asoy.parse("3|   ASOY Ankkalinna |  Katu 2  |10800|Ankkalinna     |   Isännöinti Siipiveikot   |   Huolto Räpylä"); 
    assertEquals("From: Asoy line: 267", true, asoy.toString().startsWith("3|ASOY Ankkalinna|Katu 2|10800|Ankkalinna|Isännöinti Siipiveikot|Huolto Räpylä")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone285 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone285() throws CloneNotSupportedException {    // Asoy: 285
    Asoy asoy1 = new Asoy(); 
    asoy1.parse("   3  |  Ankka Aku   | 123"); 
    Asoy kopio = asoy1.clone(); 
    assertEquals("From: Asoy line: 291", asoy1.toString(), kopio.toString()); 
    asoy1.parse("   4  |  Ankka Tupu   | 123"); 
    assertEquals("From: Asoy line: 294", false, kopio.toString().equals(asoy1.toString())); 
  } // Generated by ComTest END
}