package tietorakenne.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tietorakenne.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.04.26 10:58:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AsukasTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi115 */
  @Test
  public void testRekisteroi115() {    // Asukas: 115
    Asukas aku1 = new Asukas(); 
    assertEquals("From: Asukas line: 117", 0, aku1.getAsukasId ()); 
    aku1.rekisteroi(); 
    Asukas aku2 = new Asukas(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getAsukasId(); 
    int n2 = aku2.getAsukasId(); 
    assertEquals("From: Asukas line: 123", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone135 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone135() throws CloneNotSupportedException {    // Asukas: 135
    Asukas asukas = new Asukas(); 
    asukas.parse("   3  |  Ankka Aku   | 123"); 
    Asukas kopio = asukas.clone(); 
    assertEquals("From: Asukas line: 141", asukas.toString(), kopio.toString()); 
    asukas.parse("   4  |  Ankka Tupu   | 123"); 
    assertEquals("From: Asukas line: 144", false, kopio.toString().equals(asukas.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi231 */
  @Test
  public void testGetNimi231() {    // Asukas: 231
    Asukas aku = new Asukas(); 
    aku.taytaAkuAnkkaTiedoilla(); 
    { String _l_=aku.getNimi(),_r_="Aku Ankka.*"; if ( !_l_.matches(_r_) ) fail("From: Asukas line: 234" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString281 */
  @Test
  public void testToString281() {    // Asukas: 281
    Asukas asukas = new Asukas(); 
    asukas.parse("3| 2   |Ankka Aku    |030201-111C   |A   | 2 |04013131313|akuankka@gmail.com|0|0.0|0.0|0|puheenjohtaja||"); 
    assertEquals("From: Asukas line: 284", true, asukas.toString().startsWith("3|2|Ankka Aku|030201-111C|A|2|04013131313|akuankka@gmail.com|0|0.0|0.0|0|puheenjohtaja||")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse299 */
  @Test
  public void testParse299() {    // Asukas: 299
    Asukas asukas = new Asukas(); 
    asukas.parse("3| 2   |Ankka Aku    |030201-111C   |A   | 2 |04013131313|akuankka@gmail.com|0|0.0|0.0|0|puheenjohtaja||"); 
    assertEquals("From: Asukas line: 302", true, asukas.toString().startsWith("3|2|Ankka Aku|030201-111C|A|2|04013131313|akuankka@gmail.com|0|0.0|0.0|0|puheenjohtaja||")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPuhelinnumero352 */
  @Test
  public void testGetPuhelinnumero352() {    // Asukas: 352
    Asukas aku = new Asukas(); 
    aku.taytaAkuAnkkaTiedoilla(); 
    { String _l_=aku.getPuhelinnumero(),_r_="04013131313"; if ( !_l_.matches(_r_) ) fail("From: Asukas line: 355" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetRappu376 */
  @Test
  public void testGetRappu376() {    // Asukas: 376
    Asukas aku = new Asukas(); 
    aku.taytaAkuAnkkaTiedoilla(); 
    { String _l_=aku.getRappu(),_r_="A"; if ( !_l_.matches(_r_) ) fail("From: Asukas line: 379" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetEmail424 */
  @Test
  public void testGetEmail424() {    // Asukas: 424
    Asukas aku = new Asukas(); 
    aku.taytaAkuAnkkaTiedoilla(); 
    { String _l_=aku.getEmail(),_r_="akuankka@gmail.com"; if ( !_l_.matches(_r_) ) fail("From: Asukas line: 427" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetYhtiovastikeM2483 */
  @Test
  public void testGetYhtiovastikeM2483() {    // Asukas: 483
    Asukas aku = new Asukas(); 
    aku.taytaAkuAnkkaTiedoilla(); 
    { String _l_=aku.getYhtiovastikeM2(),_r_="10.0"; if ( !_l_.matches(_r_) ) fail("From: Asukas line: 486" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetHallitus594 */
  @Test
  public void testGetHallitus594() {    // Asukas: 594
    Asukas aku = new Asukas(); 
    aku.taytaAkuAnkkaTiedoilla(); 
    { String _l_=aku.getHallitus(),_r_="puheenjohtaja"; if ( !_l_.matches(_r_) ) fail("From: Asukas line: 597" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}