package tietorakenne.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tietorakenne.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.04.26 14:06:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {



  // Generated by ComTest BEGIN
  /** testHaeAsoyTiedot207 */
  @Test
  public void testHaeAsoyTiedot207() {    // Rekisteri: 207
    Rekisteri rekisteri = new Rekisteri(); 
    Asoy asoy = new Asoy(); 
    asoy.vastaaPitsinNyplays(1); 
    asoy.rekisteroi(); 
    rekisteri.lisaa(asoy); 
    int asoyId = asoy.getTunnusNro(); 
    String[] arvot = rekisteri.haeAsoyTiedot(asoyId); 
    assertEquals("From: Rekisteri line: 218", asoy.getAsoyNimi(), arvot[0]); 
    assertEquals("From: Rekisteri line: 219", asoy.getAsoyOsoite(), arvot[1]); 
    assertEquals("From: Rekisteri line: 220", asoy.getAsoyPostinumero(), arvot[2]); 
    assertEquals("From: Rekisteri line: 221", asoy.getAsoyPostitoimipaikka(), arvot[3]); 
    assertEquals("From: Rekisteri line: 222", asoy.getAsoyHuolto(), arvot[4]); 
    assertEquals("From: Rekisteri line: 223", asoy.getAsoyIsannoitsija(), arvot[5]); 
  } // Generated by ComTest END
}